/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MapApp: typeof import('./src/components/mapApp.vue')['default']
    MarkerInfoPop: typeof import('./src/components/markerInfoPop.vue')['default']
    OlMapApp: typeof import('./src/components/olMapApp.vue')['default']
    OlvueMapApp: typeof import('./src/components/olvueMapApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
